# Generated by Django 4.2.20 on 2025-05-22 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_step_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='reciperating',
            name='rating',
            field=models.PositiveIntegerField(help_text='Рейтинг от 0 до 5', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
